windowrule {
  name = ignore-maximize-requests
  match:class = .*
  suppress_event = maximize
}

windowrule {
  name = xwayland-dragging-fix
  match:class = ^$
  match:float = 1
  match:xwayland = 1
  match:fullscreen = 0
  match:pin = 0

  no_focus = on
}

windowrule {
  name = kitty-opacity
  match:class = kitty

  opacity = 0.9
}

windowrule {
  name = vscode-specials
  match:class = code

  no_blur = on
}

windowrule {
  name = border-when-floating
  match:float = 1

  border_size = 3
}

# SMART GAPS
# https://wiki.hypr.land/Configuring/Workspace-Rules/#smart-gaps
# Use window gaps when only at least 2 windows (floating windows and special workspace aren't affected).
workspace = w[tv1]s[false], gapsout:0, gapsin:0
workspace = f[1]s[false], gapsout:0, gapsin:0

windowrule {
  name = smart_gaps_window
  match:float = 0
  match:workspace = w[tv1]s[false]

  border_size = 0
  rounding = 0
  no_shadow = 1
}

windowrule {
  name = smart_gaps_window_2
  match:float = 0
  match:workspace = f[1]s[false]

  border_size = 0
  rounding = 0
  no_shadow = 1
}